### ISSUE TITLE
Bug in experience points

### ISSUE THREAD

**Issue by dorfo-dev** [timongorpg/timongo-old#38]
![screenshot from 2017-03-22 10-18-42](https://cloud.githubusercontent.com/assets/9588535/24199661/4588a1dc-0ee9-11e7-8a64-9b0af1d90be1.png)

**Comment by mklemersson** [comment]
I also reported that

**Comment by edddieee** [comment]
Is the bug the numeric scale in experience point?

**Comment by mklemersson** [comment]
Yes @eddiecode, I think that we could round this number in experience points

**Comment by edddieee** [comment]
@MichaelKlemersson but there is an important point here. This number without the numeric scale precision is important for another operation? If it is, we need use a Decorator Pattern to change the numeric scale only in the view, what do you think @MichaelKlemersson @hudsonpereira ?

**Comment by hudsonpereira** [comment]
It's safe to [round](http://php.net/round) it then [intval](http://php.net/intval)

**Comment by edddieee** [comment]
Yeah, you right. But I think we can use only the `(int)` to convert `float` to `int`

**Comment by hudsonpereira** [comment]
@eddiecode this way 3.5 becomes 3. We just truncate the value. We need to actually round it.

**Comment by hudsonpereira** [comment]
![screen shot 2017-03-22 at 14 04 20](https://cloud.githubusercontent.com/assets/911094/24210634/781f5c2a-0f08-11e7-818c-1373cd869d0b.png)

**Comment by mklemersson** [comment]
why we only rout in the view? I think that's better as @eddiecode said, but we need to know if we can round before send to database, no?

**Comment by edddieee** [comment]
@MichaelKlemersson we don't store this information into database. I check the method and I think there is no problem to round the experience value.(https://github.com/timongorpg/timongo/blob/master/app/Timongo/Battle/PvE.php#L72)

**Comment by hudsonpereira** [comment]
Thanks @eddiecode !
