### ISSUE TITLE
Add tests to the new features

### ISSUE THREAD

**Issue by edddieee** [timongorpg/timongo-old#45]
Hey guys, 

I think that this project is growing up fast, and big projects needs more caution. 

With the intention to avoid bugs and regressions, I added and setup a testing environment with [Kahlan Testing Framework](https://kahlan.github.io/docs/).

I think for the next `features` added to the projects, we could added tests for all use cases, and also we need to added tests to olds files.

I setup the testing environment into this PR with a complete HomeController test as an example https://github.com/timongorpg/timongo/pull/44

Let me know what you guys think about it. 🚀

**Comment by hudsonpereira** [comment]
Hey @eddiecode thanks for the amazing initiative. Tonight I'll review it all, i hope you join us tonight for the next few feature planning as well.
