### ISSUE TITLE
Monsters should have behavior

### ISSUE THREAD

**Issue by hudsonpereira** [timongorpg/timongo-old#61]
Although this is an issue to myself, you can still contribute sharing your thoughts.

### Autoscaling

Every monster should have their own `Class` and this class should tell how it autoscales e.g:

Level 1 rat has 3 attack, 1 defence and 10 hitpoints.
Level 3 rat has 5 attack, 2 defence and 20 hitpoints.

And so on.

### Behaviors

An enemy should have its on fighting behavior. e.g:

A `Mountain Dragon`'s attack should ignore armor.
A `Black Witch` should try to drain the player's mana points.

### Hunting

Enemies should not be available all the time. This one is just a thought, but I've been thinking something like __Adventure Quest__, where you fight a random monster.

**Comment by heltonteixeira** [comment]
Auto scaling and behaviors will be a nice touch to the game.

Are you planing to set the Adventure Quest as a replacement for the actual Adventures?
I have some ideas for a Quest system, is that ok if I submit a new issue with my ideas?

**Comment by hudsonpereira** [comment]
hey @heltonteixeira, yes you can open a new issue to talk about the quest system.

**Comment by hudsonpereira** [comment]
I want to bring the whole D&D System into an agnostic well-structured PHP Package. Starting with the creatures. 💀 

Here is an example of how it should be designed. I'll create a new `timongorpg/` for this purpose and address this issue with the link later on.

```php
abstract class TrollRace
{
    private $type = "Giant";
    
    // base troll race attributes
}
```

```php
class DesertTroll extends TrollRace
{
    private $description = "Chameleon-like, intelligent ambush hunters.";

    // desert troll attributes
}
```

I will really need help on this one.

**Comment by hudsonpereira** [comment]
**It's on!**

Moving this issues over there.

📦  https://github.com/timongorpg/monsters
